### ISSUE TITLE
babel-import error about importing a type

### ISSUE THREAD

**Issue by konicyQWQ** [speedy-js/speedy-native#28]
### SourceCode

```ts
import { InputProps } from "antd";

{
    let InputProps = 1;
    console.log(InputProps);
}

function App(props: InputProps) {}
```

### Expected result

```ts
import { InputProps } from "antd";

{
    let InputProps = 1;
    console.log(InputProps);
}

function App(props: InputProps) {}
```

### Unexpected result

```ts
import "antd/es/input-props/style/index.css";
import { InputProps } from "antd/es/input-props/index.js";
{
    let InputProps = 1;
    console.log(InputProps);
}
function App(props: InputProps) {}
```

That is because babel-import not call `resolve` first, which make type resolving `mark` incorrectly.

## How to Fix

- call `resolver` first to make `mark` correctly
- if a type is referenced, still remain it in origin `import`.

for example
```ts
import { InputProps, Input } from 'antd'
```
should be
```ts
import "antd/es/input/style/index.css";
import Input from "antd/es/input/index.js";
import { InputProps } from 'antd'
```

**Comment by h-a-n-a** [comment]
IMHO, the ideal result of the first example would be like this: 

```javascript
{
    let InputProps = 1;
    console.log(InputProps);
}
function App(props) {}
```

Since the reference to `InputProps` is a type, It should be removed.

**Comment by konicyQWQ** [comment]
I think so. I should remove type in import, but should I remove type in ts_type_ref?


For below example.

```ts
import { InputProps } from 'antd'

type Props = InputProps & {
    num: number;
}

function App(props: Props) {}
```

Program can find `InputProps` is a type. It can remove `InputProps` from import. Then the code will like this.

```ts
type Props = InputProps & {
             ~~~~~~~~~~
    num: number;
}

function App(props: Props) {}
```

But what about `~~~`?
Should I remain it or simply remove all types?

**Comment by h-a-n-a** [comment]
> I think so. I should remove type in import, but should I remove type in ts_type_ref?
> 
> For below example.
> 
> ```ts
> import { InputProps } from 'antd'
> 
> type Props = InputProps & {
>     num: number;
> }
> 
> function App(props: Props) {}
> ```
> 
> Program can find `InputProps` is a type. It can remove `InputProps` from import. Then the code will like this.
> 
> ```ts
> type Props = InputProps & {
>              ~~~~~~~~~~
>     num: number;
> }
> 
> function App(props: Props) {}
> ```
> 
> But what about `~~~`? Should I remain it or simply remove all types?

The final result is in pure JavaScript. Stripping typescript types is done by the code generator internally. Omit me if you mean by the current pass result.
